### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by Mahantor** [zotune/auto-install#1]
good project but not working in windows 11

**Comment by zotune** [comment]
works for me on Windows 11. did you follow the instructions using autohotkey version 1.1? it was even created on windows 11

**Comment by Mahantor** [comment]
Yes, AutoHotkey_1.1.37.02_setup.exe version
I downloaded

https://github.com/user-attachments/assets/c7e93b20-7613-4556-955d-3a9506fd8045

**Comment by zotune** [comment]
ah yeah. looking at the video. you need to copy or download Audacity to Downloads while auto-install is running and listening (WatchFolder only listens for new files/folders). it will install automatically. it will not work if Audacity is already in Downloads folder while you open the application.

![image](https://github.com/user-attachments/assets/c9d6f661-7c1d-47e0-8b70-3aeba27a07db)
